// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfyln6nD71nJ31qfPV6-r0l-8lWV_670c',
    appId: '1:41401140527:web:e5c9ceb1ed6dc5b9114dda',
    messagingSenderId: '41401140527',
    projectId: 'smart-crop-advisory-1c2be',
    authDomain: 'smart-crop-advisory-1c2be.firebaseapp.com',
    storageBucket: 'smart-crop-advisory-1c2be.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvM0ZMaTjQBwgPTgfLJttSkB8EtuOydXc',
    appId: '1:41401140527:android:626d5dfaf6bafa54114dda',
    messagingSenderId: '41401140527',
    projectId: 'smart-crop-advisory-1c2be',
    storageBucket: 'smart-crop-advisory-1c2be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSDgJ0TDrmZv-JJEklzcKGPr6rOkhehf8',
    appId: '1:41401140527:ios:fad05c669c70bca9114dda',
    messagingSenderId: '41401140527',
    projectId: 'smart-crop-advisory-1c2be',
    storageBucket: 'smart-crop-advisory-1c2be.firebasestorage.app',
    iosBundleId: 'com.example.smartCropApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSDgJ0TDrmZv-JJEklzcKGPr6rOkhehf8',
    appId: '1:41401140527:ios:fad05c669c70bca9114dda',
    messagingSenderId: '41401140527',
    projectId: 'smart-crop-advisory-1c2be',
    storageBucket: 'smart-crop-advisory-1c2be.firebasestorage.app',
    iosBundleId: 'com.example.smartCropApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfyln6nD71nJ31qfPV6-r0l-8lWV_670c',
    appId: '1:41401140527:web:9381f07bc6de2a19114dda',
    messagingSenderId: '41401140527',
    projectId: 'smart-crop-advisory-1c2be',
    authDomain: 'smart-crop-advisory-1c2be.firebaseapp.com',
    storageBucket: 'smart-crop-advisory-1c2be.firebasestorage.app',
  );
}
